name: 1. Strapi Image Building CI

on:
  push:
    branches: ["trunk"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/badgerbloke-strapi .

      - name: Push to DockerHub
        run: docker push ${{secrets.DOCKER_USERNAME}}/badgerbloke-strapi:latest
